CREATE DATABASE QLCH_OOP
USE QLCH_OOP

CREATE TABLE KHACHHANG
(
	MaKH VARCHAR(50) PRIMARY KEY,
	Tenkh NVARCHAR(100),
	GioiTinh NVARCHAR(4) DEFAULT N'Nam',
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(15),
	Email VARCHAR(100),
	MatKhau VARCHAR(100)
)

CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(50) PRIMARY KEY,
	TenNV NVARCHAR(100),
	GioiTinh NVARCHAR(4) DEFAULT N'Nam',
	SoDT VARCHAR(15),
	NgayVaoLam date,
	Luong DECIMAL(18, 2),
	TrangThai NVARCHAR(100)
)

CREATE TABLE SANPHAM 
(
	MaSP VARCHAR(50) PRIMARY KEY,
	MaDanhMuc VARCHAR(50),
	TenSP NVARCHAR(100),
	LoaiSP NVARCHAR(50),
	Gia DECIMAL(18, 2),
	FOREIGN KEY (MaDanhMuc) REFERENCES DANHMUCSANPHAM(MaDanhMuc)
)

CREATE TABLE DANHMUCSANPHAM 
(
	MaDanhMuc VARCHAR(50) PRIMARY KEY,
	TenDanhMuc NVARCHAR(100),
	MoTa NVARCHAR(100)
)

CREATE TABLE DONHANG
(
	MaDH VARCHAR(50) PRIMARY KEY,
	MaNV VARCHAR(50),
	MaKH VARCHAR(50),
	MaKM VARCHAR(50),
	NgayDatHang DATE,
	TongTien DECIMAL(18, 2),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
)

CREATE TABLE CHITIETDH
(
	MaCTDH VARCHAR(50) PRIMARY KEY,
	MaDH VARCHAR(50),
	MaSP VARCHAR(50),
	SoLuong INT,
	DonGia DECIMAL(18, 2),
	FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
)

CREATE TABLE KHUYENMAI
(
	MaKM VARCHAR(50) PRIMARY KEY,
	TenKM NVARCHAR(100),
	MoTa NVARCHAR(255),
	DieuKien NVARCHAR(255),
	LoaiKM NVARCHAR(50),
	NgayBatDau DATE,
	NgayKetThuc DATE
)